apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-node
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: aws-node
  template:
    metadata:
      labels:
        app: aws-node
    spec:
      containers:
        - name: scalex-demo
          image: scalexdemo/scalex-demo:scalex-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: aws-node
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    k8s-app: aws-node
