apiVersion: apps/v1
kind: Deployment
metadata:
name: demo
labels:
  app: demo
spec:
strategy:
  type: Recreate
template:
  metadata:
    labels:
      app: demo
      tier: demo
  spec:
    containers:
    - name: demo
      image: scalexdemo/scalex-demo:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 5000
        name: demo

---
apiVersion: v1
kind: Service
metadata:
name: demo
labels:
  app: demo
spec:
ports:
  - port: 5000
    targetPort: 5000
selector:
  app: demo
  tier: demo
type: LoadBalancer
