apiVersion: apps/v1
kind: Deployment
metadata:
name: demo
labels:
  app: scalex-demo
spec:
strategy:
  type: Recreate
template:
  metadata:
    labels:
      app: scalex-demo
      tier: scalex-demo
  spec:
    containers:
    - name: scalex-demo
      image: scalexdemo/scalex-demo:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 5000
        name: scalex-demo

---
apiVersion: v1
kind: Service
metadata:
name: scalex-demo
labels:
  app: scalex-demo
spec:
ports:
  - port: 5000
    targetPort: 5000
selector:
  app: scalex-demo
  tier: scalex-demo
type: LoadBalancer
